import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import { GetServerSideProps, GetServerSidePropsResult } from 'next'
import axios from 'axios'

export interface User {
    userId: number
    id: number
    name: string
    completed: boolean
}

interface Props {
    users: User[]
}

export default function About(props: Props) {
    // const [posts, setPosts] = useState([])

    // useEffect(() => {
    //     fetch('https://jsonplaceholder.typicode.com/posts')
    //     .then(res => res.json())
    //     .then(data => {setPosts(data)
    //     })
    //   },[])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h2>サーバーサイドで取得したデータなので、ブラウザのJSを無効にしても表示できます</h2>
        <div style={{textAlign:"start"}}>
        {props.users.map((user: User, index)=>{
            return <div key={index.toString()}>
                <li>{user.id}</li>
                <li>{user.name}</li>
                </div> 
        })}
        </div>
      </main>
    </>
  )
}

export const getServerSideProps = async ():Promise<GetServerSidePropsResult<Props>> => {
    const users: User[] = await (await axios.get("https://jsonplaceholder.typicode.com/users")).data

    return {
      props:{
        users,
      }
    }
}